### ISSUE TITLE
Possibly overflow in shift

### ISSUE THREAD

**Issue by harbaum** [fischertechniker/ROBO-Pro-for-ftDuino#1]
These lines imho cause an overflow during shift:

https://github.com/fischertechniker/ROBO-Pro-for-ftDuino/blob/baa046119ae8d68ca95fecb0ad576dbed4d63f63/utils.ino#L40-L41

I think you'll need to cast to 32 bit explicitely before shifting e.g. like so:
```
value += (UINT32)*(pData+2) << 16;
value += (UINT32)*(pData+3) << 24;
```

**Comment by fischertechniker** [comment]
Thanks for the hint - I just fixed it.
